version: "3.7"

services:
  nginx:
    build: ./nginx
    image: 
    container_name: core_proj_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - django_static:/var/www/core_proj/static
      - django_media:/var/www/core_proj/media
      - logs:/var/log/nginx
    depends_on:
      - django
  django:
    build:
      context: ./django
      args:
        MODE: production
    image:
    restart: always
    env_file:
      - ./envs/postgres.env
    environment:
      MODE: production
      STATIC_ROOT: /var/www/core_proj/static
      MEDIA_ROOT: /var/www/core_proj/media
      LOGS_ROOT: /var/log/core_proj
      NUM_GUNICORN_WORKERS: 4
      DJANGO_PORT: 8000
    logging:
      options:
        max-size: 1g
    volumes:
      - django_static:/var/www/core_proj/static
      - django_media:/var/www/core_proj/media
      - logs:/var/log/core_proj

volumes:
  django_static:
  django_media:
  logs:
