version: "3.7"

services:
  postgres:
    image: postgres:12
    container_name: media_analysis_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django:
    container_name: media_analysis_django
    working_dir: /code
    command: ["./docker/wait_db.sh", "./docker/start.sh"]
    depends_on:
      - postgres



volumes:
  postgres_data:
