strictness: veryhigh

ignore-paths:
  - migrations
  - backups
  - .venv

uses:
  - django

pep8:
  full: true
  options:
    max-line-length: 120


pylint:
  full: true

mccabe:
  disable:
    - MC0001
